INSERT INTO countries (nationality,name) VALUES
 ("Venezolana","Venezuela"),
("Afgana","Afganistán"),
("Albanesa","Albania"),
("Alemana","Alemania"),
("Alto volteña","Alto volta"),
("Andorrana","Andorra"),
("Angoleña","Angola"),
("Argelina","Argelia"),
("Argentina","Argentina"),
("Australiana","Australia"),
("Austriaca","Austria"),
("Bahamesa","Bahamas"),
("Bahreina","Bahrein"),
("Bangladesha","Bangladesh"),
("Barbadesa","Barbados"),
("Belga","Belgica"),
("Beliceña","Belice"),
("Bermudesa","Bermudas"),
("Birmana","Birmania"),
("Boliviana","Bolivia"),
("Botswanesa","Botswana"),
("Brasileña","Brasil"),
("Bulgara","Bulgaria"),
("Burundesa","Burundi"),
("Butana","Butan"),
("Camboyana","Khemer Rep de Camboya "),
("Camerunesa","Camerun"),
("Canadiense","Canada"),
("Centroafricana","Rep Centroafricana"),
("Chadeña","Chad"),
("Checoslovaca","Rep. Checa"),
("Chilena","Chile"),
("China","China"),
("China","Taiwan"),
("Chipriota","Chipre"),
("Colombiana","Colombia"),
("Congoleña","Congo"),
("Costarricense","Costa Rica"),
("Cubana","Cuba"),
("Dahoneya","Dahoney"),
("Danes","Dinamarca"),
("Dominicana","Rep. Dominicana"),
("Ecuatoriana","Ecuador"),
("Egipcia","Egipto"),
("Emirata","Emiratos Arabes Udo."),
("Escosesa","Escocia"),
("Eslovaca","Rep. Eslovaca"),
("Española","España"),
("Estona","Estonia"),
("Etiope","Etiopia"),
("Fijena","Fiji"),
("Filipina","Filipinas"),
("Finlandesa","Finlandia"),
("Francesa","Francia"),
("Gabiana","Gambia"),
("Gabona","Gabon"),
("Galesa","Gales"),
("Ghanesa","Ghana"),
("Granadeña","Granada"),
("Griega","Grecia"),
("Guatemalteca","Guatemala"),
("Guinesa Ecuatoriana","Guinea Ecuatorial"),
("Guinesa","Guinea"),
("Guyanesa","Guyana"),
("Haitiana","Haiti"),
("Holandesa","Holanda"),
("Hondureña","Honduras"),
("Hungara","Hungria"),
("India","India"),
("Indonesa","Indonesia"),
("Inglesa","Inglaterra"),
("Iraki","Irak"),
("Irani","Iran"),
("Irlandesa","Irlanda"),
("Islandesa","Islandia"),
("Israeli","Israel"),
("Italiana","Italia"),
("Jamaiquina","Jamaica"),
("Japonesa","Japon"),
("Jordana","Jordania"),
("Katensa","Katar"),
("Keniana","Kenia"),
("Kuwaiti","Kwait"),
("Laosiana","Laos"),
("Leonesa","Sierra leona"),
("Lesothensa","Lesotho"),
("Letonesa","Letonia"),
("Libanesa","Libano"),
("Liberiana","Liberia"),
("Libeña","Libia"),
("Liechtenstein","Liechtenstein"),
("Lituana","Lituania"),
("Luxemburgo","Luxemburgo"),
("Madagascar","Madagascar"),
("Malaca","Fede. de Malasia"),
("Malawi","Malawi"),
("Maldivas","Maldivas"),
("Mali","Mali"),
("Maltesa","Malta"),
("Marfilesa","Costa de Marfil"),
("Marroqui","Marruecos"),
("Mauricio","Mauricio"),
("Mauritana","Mauritania"),
("Mexicana","México"),
("Monaco","Monaco"),
("Mongolesa","Mongolia"),
("Nauru","Nauru"),
("Neozelandesa","Nueva Zelandia"),
("Nepalesa","Nepal"),
("Nicaraguense","Nicaragua"),
("Nigerana","Niger"),
("Nigeriana","Nigeria"),
("Norcoreana","Corea del Norte"),
("Norirlandesa","Irlanda del norte"),
("Norteamericana","Estados unidos"),
("Noruega","Noruega"),
("Omana","Oman"),
("Pakistani","Pakistan"),
("Panameña","Panama"),
("Paraguaya","Paraguay"),
("Peruana","Peru"),
("Polaca","Polonia"),
("Portoriqueña","Puerto Rico"),
("Portuguesa","Portugal"),
("Rhodesiana","Rhodesia"),
("Ruanda","Ruanda"),
("Rumana","Rumania"),
("Rusa","Russia"),
("Salvadoreña","El Salvador"),
("Samoa Occidental","Samoa Occidental"),
("San marino","San Marino"),
("Saudi","Arabia Saudita"),
("Senegalesa","Senegal"),
("Sikkim","Sikkim"),
("Singapur","Singapur"),
("Siria","Siria"),
("Somalia","Somalia"),
("Sovietica","Union Sovietica"),
("Sri Lanka","Sri Lanka (Ceylan) "),
("Suazilandesa","Suazilandia"),
("Sudafricana","Sudafrica"),
("Sudanesa","Sudan"),
("Sueca","Suecia"),
("Suiza","Suiza"),
("Surcoreana","Corea del Sur"),
("Tailandesa","Tailandia"),
("Tanzana","Tanzania"),
("Tonga","Tonga"),
("Tongo","Tongo"),
("Trinidad y Tobago","Trinidad y Tobago"),
("Tunecina","Tunez"),
("Turca","Turquia"),
("Ugandesa","Uganda"),
("Uruguaya","Uruguay"),
("Vaticano","Vaticano"),
("Vietnamita","Vietnam"),
("Yemen Rep Arabe","Yemen Rep. Arabe"),
("Yemen Rep Dem","Yemen Rep. Dem"),
("Yugoslava","Yugoslavia"),
("Zaire","Zaire");